version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_postgres.sql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # My system does not like the standard port on the host system
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: ./backend
    image: student_management_goapp:dev
    container_name: student_management_goapp
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}

      # for debugging air
      AIR_DEBUG: 1
    volumes:
      - ./backend/:/app
      # Cache Go modules
      - go-mod-cache:/go/pkg/mod
    depends_on:
      postgres:
        condition: service_healthy
      weaviate:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  go-mod-cache:

